Hw1
polina-pavlova/epam_python_feb21 pull request #1
Opened 2021-03-03 22:36 UTC by polina-pavlova

Homework 1 for review

2021-03-05 12:27 UTC, PeppaTheC requested changes

2021-03-05 12:27 UTC, PeppaTheC commented on homework1/tasks/task04.py
> +def check_sum_of_four(a: List[int], b: List[int], c: List[int], d: List[int]) -> int:
Решение неправильное. При таких входных данных [-1, -1], [0, 0], [0, 0], [1, 1]. Ответ должен быть 2.

2021-03-05 12:27 UTC, PeppaTheC commented on homework1/sample_project/requirements.txt
> +pytest-sugar
Тут не все зависимости проекта. И разве это самый удобный способ хранить requirements внутри папки с первым дз?

2021-03-05 12:27 UTC, PeppaTheC commented on homework1/tasks/task02.py
> +    assert len(data) >= 3
Почему не стоит использовать assert?

2021-03-05 12:27 UTC, PeppaTheC commented on homework1/tasks/task02.py
> +    while len(data) >= 3:
Решение слишком усложнено можно сделать проще

2021-03-05 12:27 UTC, PeppaTheC commented on homework1/tasks/task03.py
> +        return tuple([min_tup, max_tup])
Зачем тут явное преобразование типов?

2021-03-05 12:27 UTC, PeppaTheC commented on homework1/tasks/task03.py
> +        for line in fi:
лушче использовать list comprehension

2021-03-05 12:27 UTC, PeppaTheC commented on homework1/tests/test_task02.py
> +                0,
Тут точно нужна такая большая последовательность чисел?

2021-03-05 20:32 UTC, polina-pavlova commented on homework1/tasks/task04.py
> +def check_sum_of_four(a: List[int], b: List[int], c: List[int], d: List[int]) -> int:
Странно, у меня на таких входных данных результат 2. Добавила такие данные в тесты, проходят все, не понимаю в чем ошибка  тогда ...

2021-03-05 20:32 UTC, polina-pavlova commented on homework1/sample_project/requirements.txt
> +pytest-sugar
Файл переместила в корень проекта. Про зависимости -- добавила black и isort. Больше не использовалось ничего из не стандартной библиотеки

2021-03-05 20:32 UTC, polina-pavlova commented on homework1/tasks/task02.py
> +    assert len(data) >= 3
в данном случае, если передать список меньше чем из трех элементов, программа сразу выдаст ошибку, а следовало бы просто вернуть False

2021-03-05 20:36 UTC, polina-pavlova commented on homework1/tasks/task02.py
> +    while len(data) >= 3:
Попробовала сделать по-другому

2021-03-07 12:35 UTC, PeppaTheC commented on homework1/tasks/task04.py
> +def check_sum_of_four(a: List[int], b: List[int], c: List[int], d: List[int]) -> int:
очень извиняюсь ответ 4. Там опечатка. А у тебя два.

2021-03-07 12:43 UTC, PeppaTheC requested changes

2021-03-07 12:43 UTC, PeppaTheC commented on homework1/tasks/task02.py
> +    else:
зачем тут блок else?

2021-03-07 12:43 UTC, PeppaTheC commented on homework1/tasks/task03.py
> +        tup = [int(line) for line in fi]
что значит название этой переменной?

2021-03-07 12:43 UTC, PeppaTheC commented on homework1/tasks/task03.py
> +    return (min(tup), max(tup))
зачем тут скобки?

2021-03-07 12:43 UTC, PeppaTheC commented on homework1/tests/test_task03.py
> +    [("tests/task03.txt", (-4, 5))],
зачем тут parametrize - если тут один набор данных?

2021-03-07 12:43 UTC, PeppaTheC commented on requirements.txt
> +isort
стоит везде версии зафиксировать

2021-03-07 13:17 UTC, PeppaTheC commented on homework1/tasks/task02.py
> +    assert len(data) >= 3
Возможно такое, что в продакшене код будет запущен и оптимизацией. А она свою очередь отключает все assert из программы. Assert нужны только для внутренних проверок программистов, если обработка ошибки эта часть логики - то нужно использовать raise Exception.

2021-03-07 14:14 UTC, polina-pavlova commented on homework1/tasks/task03.py
> +        tup = [int(line) for line in fi]
переименовала на более понятное

2021-03-07 14:22 UTC, PeppaTheC approved these changes

2021-03-07 14:22 UTC, PeppaTheC commented on requirements.txt
> +isort 5.7.0
по-моему тут что-то не так?

2021-03-07 14:22 UTC, PeppaTheC commented on homework1/tasks/task04.py
> +    for i in range(len(a)):
такое решение вызывает лишние взятие по индексу a[i]
лучше поправить просто на `for element in a`

2021-03-11 13:29 UTC, merged