homework 2
polina-pavlova/epam_python_feb21 pull request #2
Opened 2021-03-09 08:58 UTC by polina-pavlova

2021-03-14 11:04 UTC, PeppaTheC requested changes

2021-03-14 11:04 UTC, PeppaTheC commented on homework2/tasks/hw1.py
> +        all_words = [i.strip(",.:?!;\"/()»«—›‹'") for i in all_words]
предлагаю сделать расширенные string.punctuation заместо ",.:?!;\"/()»«—›‹'"

2021-03-14 11:04 UTC, PeppaTheC commented on homework2/tasks/hw1.py
> +            if char in chars:
лучше использоавть defaultdict или setdefault

2021-03-14 11:04 UTC, PeppaTheC commented on homework2/tasks/hw1.py
> +        all_words = fi.read().split()
некоторые слова разбиты переносом строк на две строки

2021-03-14 11:04 UTC, PeppaTheC commented on homework2/tasks/hw1.py
> +        words[word] = [len(word), len(set(word))]
зачем нам длина слова?

2021-03-14 11:04 UTC, PeppaTheC commented on homework2/tasks/hw1.py
> +        [",", ":", ".", "!", "»", "«", "—", "?", ";", "›", "‹", "'", "(", ")"], 0
string.punctuation

2021-03-14 11:04 UTC, PeppaTheC commented on homework2/tasks/hw2.py
> +    least_common = sorted(elements, key=elements.get, reverse=True)[-1]
sorted(elements, key=elements.get, reverse=True) - лучше сохранить в константу и не сортировать массив два раза

2021-03-14 11:04 UTC, PeppaTheC commented on homework2/tasks/hw3.py
> +    return list_of_combinations
return [list(x) for x in product(*args)]

2021-03-14 11:04 UTC, PeppaTheC commented on homework2/tasks/hw4.py
> +    def func_cache(*args):
а как же **kwargs

2021-03-14 11:04 UTC, PeppaTheC commented on homework2/tasks/hw5.py
> +    if iterable.index(current) < iterable.index(stop):
не нравится мне итерирование  append лучше брать слайс

2021-03-14 11:04 UTC, PeppaTheC commented on homework2/tasks/hw5.py
> +def custom_range(iterable, *args):
так как у нас фиксированы аргументы - распаковка тут не подходит
лучше попробуй вот с таким интерфейсом функцию сделать 

def custom_range(
    iterable_seq: Iterable, start:, end=None, step: int = 1, /
) ->list:

2021-03-14 11:04 UTC, PeppaTheC commented
нужен ребейз для того, чтобы можно было нормально читать код

2021-03-15 20:37 UTC, polina-pavlova commented on homework2/tasks/hw1.py
> +        words[word] = [len(word), len(set(word))]
нам же нужно отбирать самые длинные слова

2021-03-17 16:27 UTC, PeppaTheC approved these changes

2021-03-17 16:27 UTC, PeppaTheC commented on homework2/tasks/hw4.py
> +        if args:
что будет если одновременно и args и kwargs передать?

2021-03-17 16:27 UTC, PeppaTheC commented on homework2/tasks/hw1.py
> +            words_in_line = [word.strip(string.punctuation) for word in words_in_line]
нужно сделать extend базового string.punctuation так как, там не все символы представлены

2021-03-17 16:27 UTC, PeppaTheC commented on homework2/tasks/hw1.py
> +                line += next(line)
что делает это строка?

2021-03-17 16:27 UTC, PeppaTheC commented on requirements.txt
> +requests-mock=1.15.0
что делает requests-mock=1.15.0 в req

2021-03-18 20:59 UTC, polina-pavlova commented on requirements.txt
> +requests-mock=1.15.0
это для тестов 4-го дз

2021-03-18 20:59 UTC, polina-pavlova commented on homework2/tasks/hw1.py
> +                line += next(line)
попытка взять следующую строку. исправила

2021-03-18 21:14 UTC, polina-pavlova commented on homework2/tasks/hw4.py
> +        if args:
исправила

2021-03-23 22:13 UTC, PeppaTheC approved these changes

2021-03-23 22:55 UTC, merged