Added homework 3
polina-pavlova/epam_python_feb21 pull request #3
Opened 2021-03-11 13:27 UTC by polina-pavlova

2021-03-14 11:05 UTC, PeppaTheC commented
pyc бинарники нужно убрать из репо

2021-03-17 16:42 UTC, PeppaTheC requested changes

2021-03-17 16:42 UTC, PeppaTheC commented on homework3/task01/task01.py
> +        def func_cache(*args):
func_cache(*args: Any, **kwargs: Any) -> Any:

2021-03-17 16:42 UTC, PeppaTheC commented on homework3/task02/task02.py
> +# if __name__ == '__main__':
remove commented code

2021-03-17 16:42 UTC, PeppaTheC commented on homework3/task02/task02.py
> +    with Pool() as pool:
вопрос какое количество процессов запускается? и какое оптимальное количество?

2021-03-17 16:42 UTC, PeppaTheC commented on homework3/task02/task02.py
> +    return sum(sum_)
давай оценим время работы функции

2021-03-17 16:42 UTC, PeppaTheC commented on homework3/task03/task03.py
> +        filter_funcs.append(keyword_filter_func)
чем каждая функция в filter_funcs отличается от другой?

2021-03-17 16:42 UTC, PeppaTheC commented on homework3/tests/test_task01.py
> +    with mock.patch("func_cache", autospec=True) as patched_cache:
что означает параметр autospec

2021-03-17 16:42 UTC, PeppaTheC commented on homework3/task02/task02.py
> +def main():
давай поменяем название

2021-03-17 16:42 UTC, PeppaTheC commented on homework3/task03/task03.py
> +# example of usage:
если это не inplace тесты то код лучше убрать.

Для тренировки вынеси этот код в dossting test

2021-03-17 16:42 UTC, PeppaTheC commented on homework3/task03/task03.py
> +    def __init__(self, functions):
мне больше нравится не iterable тут получать, а делать распаковку
def __init__(self, *functions):

2021-03-17 16:42 UTC, PeppaTheC commented on homework3/tests/test_task04.py
> +def test_positive_not_armstrong_number():
давай все тесты в один через parametrize

2021-03-17 18:13 UTC, PeppaTheC commented on homework3/task03/task03.py
> +        filter_funcs.append(keyword_filter_func)
+ добавь тесты на случай make_filter(name='polly', type='bird', last_name='test').apply(sample_data)

2021-03-18 21:41 UTC, polina-pavlova commented on homework3/task02/task02.py
> +    with Pool() as pool:
запускается 8 процессов, сколько на ноутбуке есть. про оптимальное количество нашла что-то про число процессов - 1, добавила это в код

2021-03-18 23:51 UTC, polina-pavlova commented on homework3/task03/task03.py
> +    def __init__(self, functions):
не совсем понимаю, т.е. нужно пробежаться по всем *functions и создать для каждой свой self. fun?

2021-03-18 23:52 UTC, polina-pavlova commented on homework3/task03/task03.py
> +        filter_funcs.append(keyword_filter_func)
пофиксила функцию

2021-03-18 23:53 UTC, polina-pavlova commented on homework3/task02/task02.py
> +    return sum(sum_)
2.5 мин. Если в O-нотации, то должно быть O(n) для прохождения по списку, по моему, и O(n) функция суммирования

2021-03-23 22:18 UTC, PeppaTheC commented on homework3/task03/task03.py
> +    def __init__(self, functions):
нет, просто использовать распаковку и передавать функции будет удобно, не надо будет их запаковывать
`def func(*params):
    params: tuple = params

    def apply():
        return [some_func(param) for param in params]


func(1, 2, 3.0, {}, [], lambda x: x + 1)`

2021-03-24 23:44 UTC, polina-pavlova commented on homework3/tests/test_task01.py
> +    with mock.patch("func_cache", autospec=True) as patched_cache:
мок создается со спецификацией объекта, который он заменяет. мок будет иметь все аттрибуты , что и заменяемый объект. но тут это неактуально. Кажется это были попытки написать что-то с моками первый раз

2021-03-30 08:54 UTC, PeppaTheC commented on homework3/task03/task03.py
> +
```python
class Filter:
    """
    Helper filter class. Accepts a list of single-argument
    functions that return True if object in list conforms to some criteria
    """

    def __init__(self, *functions: Callable[[Any], Any]):
        self.functions = functions

    def apply(self, data: Any):
        return [item for item in data if all(i(item) for i in self.functions)]


positive_even = Filter(lambda a: a % 2 == 0, lambda a: a > 0, lambda a: isinstance(a, int))
a = positive_even.apply(range(100))
```

2021-04-01 19:11 UTC, PeppaTheC approved these changes

2021-04-01 19:25 UTC, merged