Added hw4
polina-pavlova/epam_python_feb21 pull request #4
Opened 2021-03-15 20:48 UTC by polina-pavlova

2021-03-17 17:11 UTC, PeppaTheC requested changes

2021-03-17 17:11 UTC, PeppaTheC commented on homework4/tasks/task_1_read_file.py
> +        if not float(first_line):
isinstance лучше использовать - более очевидная проверка

2021-03-17 17:11 UTC, PeppaTheC commented on homework4/tasks/task_1_read_file.py
> +            raise ValueError
это точно ValueError, и как пользователь я бы хотел увидеть, что-то кроме типа ошибки, например комментарий

2021-03-17 17:11 UTC, PeppaTheC commented on homework4/tasks/task_1_read_file.py
> +            return True
давай попытаемся сделать oneliner
return ... if ... else ...

2021-03-17 17:11 UTC, PeppaTheC commented on homework4/tasks/task_2_mock_input.py
> +import re
не используется

2021-03-17 17:11 UTC, PeppaTheC commented on homework4/tasks/task_2_mock_input.py
> +    except ValueError:
давай попробуем разные виды ошибок отловить
я уверен что там может быть не только ValueError

2021-03-17 17:11 UTC, PeppaTheC commented on homework4/tasks/task_2_mock_input.py
> +        return counter
res.text.count('i')

2021-03-17 17:11 UTC, PeppaTheC commented on homework4/tasks/task_3_get_print_output.py
> +        sys.stderr.write(text)
для ознакомления есть еще вариант делать вот так print(text, file=sys.stderr)

2021-03-17 17:11 UTC, PeppaTheC commented on homework4/tests/test_task_1.py
> +def test_negative_case_upper_boundary():
parametrize лучше использовать так как код повторяется

2021-03-17 17:11 UTC, PeppaTheC commented on homework4/tests/test_task_2.py
> +        assert ValueError
я думаю тут надо использовать 
with pytest.raises(ValueError):
    ...

и тогда вопрос, assert ValueError - что это значит? как работает assert и exception в python

2021-03-24 21:50 UTC, polina-pavlova commented on homework4/tests/test_task_2.py
> +        assert ValueError
assert для отладки кода используется, проверяет условие, и выбрасывает ошибку если оно не выполняется, по большей части в тестах. 
try-except: try -- проверка какой-то оепрации на возможные ожидаемые ошибки, except -- тип исключения, которое выбрасывается в случае неуспешного выполнения try блока.  

тест исправила

2021-03-30 08:36 UTC, PeppaTheC requested changes

2021-03-30 08:36 UTC, PeppaTheC commented on homework4/tasks/task_2_mock_input.py
> +        raise ValueError(f"Unreachable {url}")
почему же тут ValueError - если мы отвалились по ошибки ConnectionError.
RequestException уже включает в себя ошибки 
        req_exc.ConnectionError,
        req_exc.Timeout,
        req_exc.HTTPError,

2021-03-31 15:55 UTC, merged