Added homework8
polina-pavlova/epam_python_feb21 pull request #8
Opened 2021-04-06 22:16 UTC by polina-pavlova

2021-04-15 22:58 UTC, PeppaTheC requested changes

2021-04-15 22:58 UTC, PeppaTheC commented on homework8/tasks/task1.py
> +class KeyValueStorage:
nice

2021-04-15 22:58 UTC, PeppaTheC commented on homework8/tasks/task2.py
> +        cursor = self.connect_db()
it woud be nice always have one conneciton to db for class

2021-04-15 22:58 UTC, PeppaTheC commented on homework8/tasks/task2.py
> +        return cursor
does it support 
for president in presidents:
           print(president['name'])

2021-04-15 23:04 UTC, PeppaTheC commented on homework8/tasks/task2.py
> +        return cursor
for president in presidents:
           print(president['name'])

2021-04-17 15:03 UTC, polina-pavlova commented on homework8/tasks/task2.py
> +        return cursor
исправила

2021-04-18 09:28 UTC, PeppaTheC approved these changes

2021-04-18 11:40 UTC, merged